#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Term-Shell
Version  : 0.09
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Term-Shell-0.09.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Term-Shell-0.09.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libterm-shell-perl/libterm-shell-perl_0.09-1.debian.tar.xz
Summary  : 'A simple command-line shell framework.'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-2.0
Requires: perl-Term-Shell-license
Requires: perl-Term-Shell-man
Requires: perl(Module::Build)
Requires: perl(Term::ReadKey)
Requires: perl(Text::Autoformat)
BuildRequires : perl(Module::Build)
BuildRequires : perl(Term::ReadKey)
BuildRequires : perl(Text::Autoformat)

%description
This archive contains the distribution Term-Shell,
version 0.09:
A simple command-line shell framework.

%package license
Summary: license components for the perl-Term-Shell package.
Group: Default

%description license
license components for the perl-Term-Shell package.


%package man
Summary: man components for the perl-Term-Shell package.
Group: Default

%description man
man components for the perl-Term-Shell package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n Term-Shell-0.09
mkdir -p %{_topdir}/BUILD/Term-Shell-0.09/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/Term-Shell-0.09/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Term-Shell
cp LICENSE %{buildroot}/usr/share/doc/perl-Term-Shell/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Term/Shell.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Term-Shell/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Term::Shell.3
